# Generated by Django 4.1.4 on 2023-03-04 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/doctors/%y%m%d",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("username", models.CharField(blank=True, max_length=254, null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=150, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("qualifications", models.TextField(blank=True, null=True)),
                (
                    "days",
                    models.CharField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                            (7, "not determine ye"),
                        ],
                        default=7,
                        max_length=1,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={"unique_together": {("username",)},},
        ),
        migrations.CreateModel(
            name="login_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(default="patient", max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=50
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="None", null=True, upload_to="doctors/"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("username", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.IntegerField(blank=True, default="None", null=True),
                ),
                ("password", models.CharField(max_length=150)),
                ("age", models.IntegerField()),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[("cash", "cash"), ("VISA", "VISA")],
                        default="cash",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C-", "C-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("diabete", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "diabete_type",
                    models.CharField(
                        blank=True,
                        choices=[("type 1", "type 1"), ("type 2", "type 2")],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "blood_presure",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "diseases",
                    models.TextField(blank=True, default="No Diseases", null=True),
                ),
            ],
            options={"unique_together": {("username",)},},
        ),
        migrations.CreateModel(
            name="report_appiontment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "report",
                    models.TextField(blank=True, default="Not Writen yet", null=True),
                ),
                (
                    "symptoms",
                    models.TextField(blank=True, default="Not Writen yet", null=True),
                ),
                (
                    "result",
                    models.TextField(blank=True, default="Not Writen yet", null=True),
                ),
                (
                    "drugs",
                    models.TextField(blank=True, default="Not Writen yet", null=True),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.patient",
                    ),
                ),
            ],
            options={"unique_together": {("date", "time")},},
        ),
        migrations.CreateModel(
            name="secretary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/doctors/%y%m%d",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("username", models.CharField(max_length=50)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("password", models.CharField(max_length=150)),
                (
                    "working_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={"unique_together": {("username",)},},
        ),
        migrations.CreateModel(
            name="schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.report_appiontment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reset_password_token", models.CharField(max_length=100)),
                ("created_at", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
