# Generated by Django 4.1.4 on 2023-03-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="image",),
    ]
