# Generated by Django 4.1.4 on 2023-03-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_patient_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="doctor", name="image",),
        migrations.RemoveField(model_name="secretary", name="image",),
    ]
